# Generated by Django 2.0 on 2019-03-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('desciption', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124, unique=True)),
                ('price', models.IntegerField()),
                ('short_description', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('category', models.ManyToManyField(to='products.Category')),
            ],
        ),
    ]
