# Generated by Django 2.0 on 2019-03-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=124, unique=True),
        ),
    ]
